### ISSUE TITLE
JitPack builds broken

### ISSUE THREAD

**Issue by s5bug** [ITesserakt/diskordin#5]
Trying to get the current commit through JitPack breaks as it can't find artifacts.

**Comment by ITesserakt** [comment]
Thank you for opening this issue! After my experiments with new Gradle modules, JitPack seems definitely was broken. I'll try to fix it as soon as possible

**Comment by ITesserakt** [comment]
Seems to be fixed. You can add a project to your dependencies using jitpack multimodule syntax:
```groovy
implementation("com.github.ITesserakt.diskordin:{module-name}:-SNAPSHOT")
```
